تعریف ماتریس2*2 با نامپای

In [49]:
import numpy as np 
A = np.array([[6, 1, 1], 
              [4, -2, 5], 
              [2, 8, 7]]) 


محاسبه رنک ماتریس

In [50]:
print("Rank of A:", np.linalg.matrix_rank(A)) 


Rank of A: 3


اثر ماتریس = مجموع عناصر قطر اصلی

In [51]:
print("\n Trace of A:", np.trace(A)) 



 Trace of A: 11


محاسبه مقدار ویژه و بردارهای ویژه

In [52]:
print("\n eigenvalues of A:", np.linalg.eig(A))



 eigenvalues of A: (array([11.24862343,  5.09285054, -5.34147398]), array([[ 0.24511338,  0.75669314,  0.02645665],
       [ 0.40622202, -0.03352363, -0.84078293],
       [ 0.88028581, -0.65291014,  0.54072554]]))


محاسبه نرم ماتریس 

In [53]:
print(A[0:1])
print("\n norm of A:", np.linalg.norm(A[0:1]))

[[6 1 1]]

 norm of A: 6.164414002968976


محاسبه دترمینان ماتریس

In [54]:
print("\nDeterminant of A:", np.linalg.det(A)) 



Determinant of A: -306.0


محاسبه ماتریس معکوس

In [55]:
print("\nInverse of A:\n", np.linalg.inv(A)) 



Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


ماتریس به توان 3

In [56]:
print("\nMatrix A raised to power 3:\n", np.linalg.matrix_power(A, 3))



Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


y=A.x حل معادلات چند معادله چند مجهول 

In [57]:
y = np.array([[1], [2],[3]])
x=np.linalg.solve(A, y)

print("X solved: \n" , x)

X solved: 
 [[0.10130719]
 [0.05228758]
 [0.33986928]]
